# Generated by Django 4.2.5 on 2024-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "FabricaClass",
            "0006_remove_criterios_booleano_remove_criterios_numerico_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pergunta",
            name="descricao",
            field=models.CharField(default="Pergunta", max_length=255),
        ),
    ]
