# Generated by Django 4.2.5 on 2024-03-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FabricaClass", "0007_pergunta_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criterios",
            name="descricao",
            field=models.CharField(default="Criterio", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pergunta",
            name="descricao",
            field=models.CharField(default="Pergunta", max_length=255, null=True),
        ),
    ]
