# Generated by Django 4.2.5 on 2024-04-26 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("FabricaClass", "0008_alter_criterios_descricao_alter_pergunta_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="curso",
            field=models.IntegerField(
                choices=[(1, "Graduação"), (2, "Técnico")], default=2
            ),
        ),
        migrations.AddField(
            model_name="formulario",
            name="data_fim",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formulario",
            name="data_hora_limite",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formulario",
            name="data_inicio",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
