# Generated by Django 4.2.5 on 2024-04-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("FabricaClass", "0009_curso_curso_formulario_data_fim_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulario",
            name="pergunta",
        ),
        migrations.RemoveField(
            model_name="pergunta",
            name="criterio",
        ),
        migrations.RemoveField(
            model_name="respostas",
            name="formulario",
        ),
        migrations.AddField(
            model_name="criterios",
            name="pergunta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FabricaClass.pergunta",
            ),
        ),
        migrations.AddField(
            model_name="pergunta",
            name="formulario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FabricaClass.formulario",
            ),
        ),
        migrations.AddField(
            model_name="respostas",
            name="pergunta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FabricaClass.pergunta",
            ),
        ),
    ]
