# name: fabricaclass
# services:
#   db:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: fabricaclass
#     restart: always
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./db_data:/var/lib/postgresql/data
  
# volumes:
#   db_data: