# Generated by Django 4.2.5 on 2024-04-02 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0005_alter_usuario_password_reset_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="telefone",
        ),
    ]
