# Generated by Django 5.0.6 on 2024-07-09 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Criterios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(default="Criterio", max_length=255, null=True),
                ),
                ("valor_maximo", models.IntegerField(default=5)),
                ("valor_minimo", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "turno",
                    models.IntegerField(
                        choices=[
                            (1, "Matutino"),
                            (2, "Vespertino"),
                            (3, "Noturno"),
                            (4, "Integral"),
                        ],
                        default=4,
                    ),
                ),
                (
                    "curso",
                    models.IntegerField(
                        choices=[(1, "Graduação"), (2, "Técnico")], default=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora_limite", models.DateTimeField(blank=True, null=True)),
                (
                    "data_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(default="Pergunta", max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respostas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("resposta", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legenda", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "ano_letivo",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1º Ano"), (2, "2º Ano"), (3, "3º Ano")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "semestre_letivo",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (4, "1º Semestre"),
                            (5, "2º Semestre"),
                            (6, "3º Semestre"),
                            (7, "4º Semestre"),
                            (8, "5º Semestre"),
                            (9, "6º Semestre"),
                            (10, "7º Semestre"),
                            (11, "8º Semestre"),
                            (12, "9º Semestre"),
                            (13, "10º Semestre"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
