# Generated by Django 5.0.6 on 2024-07-09 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fabrica_class", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pergunta",
            name="formulario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fabrica_class.formulario",
            ),
        ),
        migrations.AddField(
            model_name="criterios",
            name="pergunta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fabrica_class.pergunta",
            ),
        ),
        migrations.AddField(
            model_name="respostas",
            name="pergunta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fabrica_class.pergunta",
            ),
        ),
        migrations.AddField(
            model_name="respostas",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Curso",
                to="fabrica_class.curso",
            ),
        ),
    ]
